//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rcmsendbackfailed
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessCallLog
    {
        public decimal CallNo { get; set; }
        public System.DateTime GenDate { get; set; }
        public System.DateTime ActionDate { get; set; }
        public System.DateTime GenTime { get; set; }
        public string Region { get; set; }
        public string Location { get; set; }
        public string Hublocation { get; set; }
        public string SubLocation { get; set; }
        public string CityCode { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerBranchCode { get; set; }
        public string CustCustomerCode { get; set; }
        public string ChildCRNno { get; set; }
        public string CompanyCode { get; set; }
        public string BankLoginNo { get; set; }
        public Nullable<System.DateTime> BankLoginTime { get; set; }
        public Nullable<int> NumberofCheques { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> RequestTime { get; set; }
        public decimal PickupAmount { get; set; }
        public Nullable<decimal> AmountDifference { get; set; }
        public string ChequeNumbers { get; set; }
        public string CallAction { get; set; }
        public string CallNature { get; set; }
        public string CallType { get; set; }
        public string CallStatus { get; set; }
        public string CallRemark { get; set; }
        public string CallRoute { get; set; }
        public string RefrenceNo1 { get; set; }
        public string RefrenceNo2 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string AuthorisedBy { get; set; }
        public Nullable<System.DateTime> AuthorisedDate { get; set; }
        public string ExecutedBy { get; set; }
        public Nullable<System.DateTime> ExecutedDate { get; set; }
        public string AttendBy { get; set; }
        public Nullable<System.DateTime> AttendDate { get; set; }
        public string AttendTime { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string NilCashReason { get; set; }
        public string BankorVault { get; set; }
        public string CallPassword { get; set; }
        public string SealBagNumber { get; set; }
        public string SealNumber { get; set; }
        public string NilConsiderChk { get; set; }
        public string CashLimitExdFlag { get; set; }
        public string HCINFlag { get; set; }
        public Nullable<decimal> RequestAmount { get; set; }
        public Nullable<decimal> RequestAmountDiff { get; set; }
        public Nullable<System.DateTime> RectificationDate { get; set; }
        public string ClosedCallEditedby1 { get; set; }
        public Nullable<System.DateTime> ClosedCallEditedDate1 { get; set; }
        public string ClosedCallEditedby2 { get; set; }
        public Nullable<System.DateTime> ClosedCallEditedDate2 { get; set; }
        public string DeliveryFundedBy { get; set; }
        public string CashWithdrawalFrom { get; set; }
        public string CashWithdrawalBranch { get; set; }
        public string CashWithdrawalLocation { get; set; }
        public string CashDeliveryTime { get; set; }
        public string receipt_print { get; set; }
        public string counter_no { get; set; }
        public string trans_id { get; set; }
        public Nullable<bool> SendSMS { get; set; }
        public Nullable<int> Reason { get; set; }
        public string HCINumber { get; set; }
        public string OtherDetail1 { get; set; }
        public string OtherDetail2 { get; set; }
        public string DepositSlipImage { get; set; }
        public string HCINOImage { get; set; }
        public string Remarks { get; set; }
        public string Flag { get; set; }
        public string HCINStartS { get; set; }
        public string HCINEndS { get; set; }
        public string HCINCurrentS { get; set; }
        public string OTP { get; set; }
        public string RemarksHCIN { get; set; }
        public string NilCashFlag { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public Nullable<decimal> ChequeAmount { get; set; }
        public string FlagMaxCashLimit { get; set; }
        public string FlagSealBag { get; set; }
        public string FlagDepositUpload { get; set; }
        public string FlagHCIUpload { get; set; }
        public string FlagHCINReplace { get; set; }
        public string HCINReplaceImg { get; set; }
        public string CallSubStatus { get; set; }
        public string FlagHCINmismatch { get; set; }
        public string FlagPISUpload { get; set; }
        public string FlagCDPDeposition { get; set; }
        public string FlagNCMDeposition { get; set; }
        public string RemarkSealBag { get; set; }
        public string FlagVaultDepositionCDP { get; set; }
        public string HCINname { get; set; }
        public string HCINmobileNo { get; set; }
        public Nullable<System.TimeSpan> HCINinTime { get; set; }
        public Nullable<System.TimeSpan> HCINoutTime { get; set; }
        public string NilIssueType { get; set; }
        public Nullable<bool> DryRunFlag { get; set; }
        public Nullable<bool> FlagClientApproval { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public byte[] TimeStramp { get; set; }
        public Nullable<int> HCINSeriesRemarkId { get; set; }
        public string Custodian1 { get; set; }
        public string Custodian2 { get; set; }
        public string Custodian3 { get; set; }
        public string Custodian4 { get; set; }
        public string PrevEmpCode { get; set; }
        public string ActualRouteId { get; set; }
        public int Id { get; set; }
        public Nullable<bool> IsDryRunSubmit { get; set; }
        public Nullable<bool> MobileUpdate { get; set; }
        public string OtherRemarksHCIN { get; set; }
        public Nullable<System.DateTime> RestartServiceDate { get; set; }
        public Nullable<decimal> OTPMobileNo { get; set; }
        public string flagidfcapisent { get; set; }
    }
}
