//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rcmsendbackfailed
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAPICallDetail
    {
        public long id { get; set; }
        public decimal CallNo { get; set; }
        public Nullable<long> CallDenoId { get; set; }
        public string UTR { get; set; }
        public Nullable<short> SerialNo { get; set; }
        public string CustomerUniqueId { get; set; }
        public Nullable<int> ClientCustAccountMasterID { get; set; }
        public string AccountId { get; set; }
        public string ClientCode { get; set; }
        public string PickupCode { get; set; }
        public string StoreCode { get; set; }
        public string HierarchyCode { get; set; }
        public string DivisionCode { get; set; }
        public string CustomerDeptCode { get; set; }
        public string SubDivisionCode { get; set; }
        public string SubCode { get; set; }
        public Nullable<int> Deno1000 { get; set; }
        public Nullable<int> Deno2000 { get; set; }
        public Nullable<int> Deno500 { get; set; }
        public Nullable<int> Deno200 { get; set; }
        public Nullable<int> Deno100 { get; set; }
        public Nullable<int> Deno50 { get; set; }
        public Nullable<int> Deno20 { get; set; }
        public Nullable<int> Deno10 { get; set; }
        public Nullable<int> DenoCoin10 { get; set; }
        public Nullable<decimal> DenoOthers { get; set; }
        public Nullable<int> Deno5 { get; set; }
        public Nullable<int> Deno2 { get; set; }
        public string DepositSlipNo { get; set; }
        public string PISNo { get; set; }
        public string RTFNo { get; set; }
        public Nullable<decimal> ActualAmount { get; set; }
        public Nullable<decimal> PickupAmont { get; set; }
        public Nullable<decimal> CashLimit { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<bool> IsMobileUpdate { get; set; }
        public string ResponseStatus { get; set; }
        public string Response { get; set; }
    }
}
